In [1]:
import numpy as np
import csv
import matplotlib.pyplot as plt
import random
import loading as ld
import implementations as imp
import confusion_matrix as conf

In [2]:
# load the data using our own method
y, X, ids = ld.load_csv_data('train.csv')
ytest, Xtest, idstest = ld.load_csv_data('test.csv')

In [3]:
np.delete(ids,[0,1])
np.delete(idstest,[0,1])

array(['DER_mass_MMC', 'DER_mass_transverse_met_lep', 'DER_mass_vis', ...,
       '-999', '-999', '48.446'], dtype='<U27')

In [4]:
# Data processing : getting rid of the columns which have "-999" values
new_X = X.copy()
new_X = np.delete(new_X, np.where(new_X == -999)[1], axis=1)
new_Xtest = Xtest.copy()
new_Xtest = np.delete(new_Xtest, np.where(new_Xtest == -999)[1], axis=1)

# the variable PRI_jet_num seems quite central, as many other variables depend on it
# here the data is separated following this fact
""""PRI_jet_num_0 = new_X[:][new_X[:,22] == 0 ]
new_PRI_jet_num_0 = PRI_jet_num_0.copy()
new_PRI_jet_num_0 = np.delete(new_PRI_jet_num_0, np.where(new_PRI_jet_num_0 == -999)[1], axis=1)

PRI_jet_num_1 = new_X[1:][new_X[1:,22] == 1]
new_PRI_jet_num_1 = PRI_jet_num_1.copy()
new_PRI_jet_num_1 = np.delete(new_PRI_jet_num_1, np.where(new_PRI_jet_num_1 == -999)[1], axis=1)

PRI_jet_num_2 = new_X[1:][new_X[1:,22] == 2]
new_PRI_jet_num_2 = PRI_jet_num_2.copy()
new_PRI_jet_num_2 = np.delete(new_PRI_jet_num_2, np.where(new_PRI_jet_num_2 == -999)[1], axis=1)

PRI_jet_num_3 = new_X[1:][new_X[1:,22] == 3]
new_PRI_jet_num_3 = PRI_jet_num_3.copy()
new_PRI_jet_num_3 = np.delete(new_PRI_jet_num_3, np.where(new_PRI_jet_num_3 == -999)[1], axis=1)"""

'"PRI_jet_num_0 = new_X[:][new_X[:,22] == 0 ]\nnew_PRI_jet_num_0 = PRI_jet_num_0.copy()\nnew_PRI_jet_num_0 = np.delete(new_PRI_jet_num_0, np.where(new_PRI_jet_num_0 == -999)[1], axis=1)\n\nPRI_jet_num_1 = new_X[1:][new_X[1:,22] == 1]\nnew_PRI_jet_num_1 = PRI_jet_num_1.copy()\nnew_PRI_jet_num_1 = np.delete(new_PRI_jet_num_1, np.where(new_PRI_jet_num_1 == -999)[1], axis=1)\n\nPRI_jet_num_2 = new_X[1:][new_X[1:,22] == 2]\nnew_PRI_jet_num_2 = PRI_jet_num_2.copy()\nnew_PRI_jet_num_2 = np.delete(new_PRI_jet_num_2, np.where(new_PRI_jet_num_2 == -999)[1], axis=1)\n\nPRI_jet_num_3 = new_X[1:][new_X[1:,22] == 3]\nnew_PRI_jet_num_3 = PRI_jet_num_3.copy()\nnew_PRI_jet_num_3 = np.delete(new_PRI_jet_num_3, np.where(new_PRI_jet_num_3 == -999)[1], axis=1)'

In [11]:
Xtest.shape

(568238, 30)

In [13]:
wls=imp.least_squares(y,X)
ychapo=Xtest.dot(wls[0])
print (ychapo.shape)
for i in range (0,len(ychapo)):
    if ychapo[i]>0.5:
        ychapo[i]=int(1)
    else:
         ychapo[i]=int(0)
conf.compute_confusion_matrix(ytest,ychapo)

(568238,)


IndexError: index 1 is out of bounds for axis 0 with size 1

In [6]:
wlsgd=imp.least_square_GD(y,X,np.ones(30),100,0.8)
ychap=Xtest.dot(wlsgd[0])
for i in range (0,len(ychap)):
    if ychap[i]>0.5:
        ychap[i]=int(1)
    else:
         ychap[i]=int(0)
conf.compute_confusion_matrix(ytest,ychap)

array([[164333.,      0.],
       [ 85667.,      0.]])

In [7]:
wls=imp.least_squares_SGD(y,X,np.ones(30),100,0.3)
ychapo=Xtest.dot(wls[0])
for i in range (0,len(ychapo)):
    if ychapo[i]>0.5:
        ychapo[i]=int(1)
    else:
         ychapo[i]=int(0)
conf.compute_confusion_matrix(ytest,ychapo)

array([[164333.,      0.],
       [ 85667.,      0.]])

In [8]:
wls=imp.ridge_regression(y,X,0.5)
ychapo=Xtest.dot(wls[0])
for i in range (0,len(ychapo)):
    if ychapo[i]>0.5:
        ychapo[i]=int(1)
    else:
         ychapo[i]=int(0)
conf.compute_confusion_matrix(ytest,ychapo)

array([[131482.,  32851.],
       [ 68846.,  16821.]])

In [9]:
wls=imp.logistic_regression(y,X,np.ones(30),100,0.1)
ychapo=Xtest.dot(wls[0])
for i in range (0,len(ychapo)):
    if ychapo[i]>0.5:
        ychapo[i]=int(1)
    else:
         ychapo[i]=int(0)
conf.compute_confusion_matrix(ytest,ychapo)

/Users/arthurbrousse/Documents/GitHub/Machine-Learning-Project/Project 1/loss_functions.py:5: RuntimeWarning: overflow encountered in exp
  return 1/(1 + np.exp(-x))
/Users/arthurbrousse/Documents/GitHub/Machine-Learning-Project/Project 1/loss_functions.py:25: RuntimeWarning: divide by zero encountered in log
  return np.sum(y * np.log(sigmoid(tx.dot(w))) + (1 - y) * np.log(1 - sigmoid(tx.dot(w))))/len(y)
/Users/arthurbrousse/Documents/GitHub/Machine-Learning-Project/Project 1/loss_functions.py:25: RuntimeWarning: invalid value encountered in multiply
  return np.sum(y * np.log(sigmoid(tx.dot(w))) + (1 - y) * np.log(1 - sigmoid(tx.dot(w))))/len(y)


array([[128113.,  36220.],
       [ 53773.,  31894.]])

In [9]:
wls=imp.reg_logistic_regression(y,X,0.1,np.ones(30),100,0.1)
ychapo=Xtest.dot(wls[0])
for i in range (0,len(ychapo)):
    if ychapo[i]>0.5:
        ychapo[i]=int(1)
    else:
         ychapo[i]=int(0)
conf.compute_confusion_matrix(ytest,ychapo)

/home/bastienll/Documents/EPFL/Master/MA1/ML_course/Machine-Learning-Project/Project 1/loss_functions.py:5: RuntimeWarning: overflow encountered in exp
  return 1/(1 + np.exp(-x))
/home/bastienll/Documents/EPFL/Master/MA1/ML_course/Machine-Learning-Project/Project 1/loss_functions.py:25: RuntimeWarning: divide by zero encountered in log
  return np.sum(y * np.log(sigmoid(tx.dot(w))) + (1 - y) * np.log(1 - sigmoid(tx.dot(w))))/len(y)
/home/bastienll/Documents/EPFL/Master/MA1/ML_course/Machine-Learning-Project/Project 1/loss_functions.py:25: RuntimeWarning: invalid value encountered in multiply
  return np.sum(y * np.log(sigmoid(tx.dot(w))) + (1 - y) * np.log(1 - sigmoid(tx.dot(w))))/len(y)


array([[128566.,  35767.],
       [ 67158.,  18509.]])

In [ ]:
#split the train.csv into a training set and a validation set
X_train, X_validate = np.split(X,[int(.5*len(X))])
y_train, y_validate = np.split(y,[int(.5*len(y))])

for the graph there needs to be no extra modifications to the csv file after it is read

In [ ]:
vecto=[]
[vecto.append(random.randrange(1,250000,1)) for i in range (1,1000)]
for i in range (2,16):
    plt.figure(i)
    plt.scatter(train[vecto,i],train[vecto,1])

In [ ]:
vecto=[]
[vecto.append(random.randrange(250000)) for i in range (1,1000)]
for i in range (17,32):
    plt.figure(i)
    plt.scatter(train[vecto,i],train[vecto,1])

In [ ]:
trainb=[]
trains=[]
for i in train[1:250000,:]:
    if i[1]=="b":
        trainb.append(i)
    else:
        trains.append(i)
trains=np.asarray(trains)
trainb=np.asarray(trainb)

In [ ]:
vecto=[]
vect=[]
[vecto.append(random.randrange(len(trainb))) for i in range (1,500)]
[vect.append(random.randrange(len(trains))) for i in range (1,500)]
print(len(vect),len(trains))
for i in range (2,5):
    for j in range (2,5):
        plt.figure(i+j)
        plt.subplot(1, 2, 1)
        plt.scatter(trainb[vecto,i],trainb[vecto,j],color='blue')
        plt.subplot(1, 2, 2)
        plt.scatter(trains[vect,i],trains[vect,j],color='red')